//LAB ACTIONS
export const ADD_LAB_DATA = 'ADD LAB DATA'
export const FETCH_LAB_DATA = 'GET LAB DATA'
export const FETCH_ONE_LAB_DATA = 'GET A LAB DATA'
export const DELETE_LAB_DATA = 'DELETE ITEM'
export const UPDATE_LAB_DATA = 'UPDATE FORM'

//PHARMACY ACTIONS
export const ADD_PHARMACY_DATA = 'ADD PHARMACY DATA'
export const FETCH_PHARMACY_DATA = 'GET PHARMACY DATA'
export const FETCH_ONE_PHARMACY_DATA = 'GET A PHARMACY DATA'
export const DELETE_PHARMACY_DATA = 'DELETE PHARMACY ITEM'
export const UPDATE_PHARMACY_DATA = 'UPDATE PHARMACY FORM'